# Generated by Django 4.2.30 on 2026-06-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_code', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('birth_weight', models.FloatField()),
                ('gestational_age', models.IntegerField()),
                ('mother_age', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
