# Generated by Django 6.0.7 on 2026-07-15 22:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_outcome_28d'),
        ('pods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaternalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_mrn', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, default='O+', max_length=10)),
                ('hiv_status', models.CharField(default='Non-reactive (Negative)', max_length=50)),
                ('gravida', models.PositiveSmallIntegerField(default=1)),
                ('parity', models.PositiveSmallIntegerField(default=0)),
                ('gestational_diabetes', models.BooleanField(default=False)),
                ('hypertension', models.BooleanField(default=False)),
                ('anc_visits', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='patient',
            name='admission_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='patient',
            name='apgar_1min',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='apgar_5min',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='bed_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='delivery_type',
            field=models.CharField(choices=[('normal_vaginal', 'Normal Vaginal'), ('emergency_csection', 'Emergency C-Section'), ('elective_csection', 'Elective C-Section'), ('assisted_forceps', 'Assisted Forceps')], default='normal_vaginal', max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='gestational_age_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='pod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='pods.pod'),
        ),
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('discharged', 'Discharged'), ('transferred', 'Transferred'), ('deceased', 'Deceased')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_weight',
            field=models.FloatField(help_text='Birth weight in kg'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gestational_age',
            field=models.IntegerField(help_text='Gestational age in weeks'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='risk_level',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Moderate', 'Moderate')], default='Low', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='maternal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neonates', to='patients.maternalprofile'),
        ),
    ]
