# Generated by Django 6.0.7 on 2026-07-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_maternalprofile_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maternalprofile',
            name='hospital_mrn',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
