# Generated by Django 6.0.7 on 2026-07-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_clear_duplicate_beds'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='apgar_1min_components',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='apgar_5min_components',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='current_weight',
            field=models.FloatField(blank=True, help_text='Latest recorded weight in kg (updated on reassess; birth_weight never changes)', null=True),
        ),
    ]
