# Generated by Django 4.2.30 on 2026-07-04 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('developer', 'Developer'), ('admin', 'Hospital Admin'), ('neonatologist', 'Neonatologist'), ('nurse', 'NICU Nurse'), ('midwife', 'Midwife'), ('lab_tech', 'Lab Technician'), ('pharmacist', 'Pharmacist'), ('researcher', 'Researcher')], default='neonatologist', max_length=20)),
                ('full_name', models.CharField(blank=True, default='', max_length=200)),
                ('hospital', models.CharField(blank=True, default='City Children Hospital', max_length=200)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
