# Generated by Django 6.0.7 on 2026-07-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamchat', '0002_teammessage_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammessage',
            name='pod_name',
            field=models.CharField(blank=True, default='', help_text='Optional pod/ward scope', max_length=100),
        ),
    ]
