# Generated by Django 6.0.7 on 2026-07-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_clinical_assessment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='birth_asphyxia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='multiple_birth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='respiratory_distress_syndrome',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='sepsis',
            field=models.BooleanField(default=False),
        ),
    ]
