# Generated by Django 6.0.7 on 2026-07-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_clinical_model_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='current_weight',
            field=models.FloatField(blank=True, help_text='Weight (kg) at assessment. Prefer this over birth_weight for risk scoring.', null=True),
        ),
    ]
