# Generated by Django 6.0.7 on 2026-07-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_assessment_current_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='apgar_1min_components',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='apgar_5min_components',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='current_weight',
            field=models.FloatField(blank=True, help_text='Weight (kg) at assessment time for clinical tracking.', null=True),
        ),
    ]
