# Generated by Django 6.0.7 on 2026-07-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_clinical_workflow_weights_apgar'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='birth_asphyxia_grade',
            field=models.CharField(blank=True, default='None', max_length=12),
        ),
        migrations.AddField(
            model_name='assessment',
            name='respiratory_distress_grade',
            field=models.CharField(blank=True, default='None', max_length=12),
        ),
    ]
